// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyB2e07_zg8iRQiD2OQNaZpmXBXuFdEAcdc',
    appId: '1:697837525606:web:2303311515ae3ce1ad2ba7',
    messagingSenderId: '697837525606',
    projectId: 'chat-app-6cd17',
    authDomain: 'chat-app-6cd17.firebaseapp.com',
    storageBucket: 'chat-app-6cd17.appspot.com',
    measurementId: 'G-CMK07Z6HJV',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyA19sL9FUxbljYeq__bYpK07c8-xunoQ6w',
    appId: '1:697837525606:android:563d28609832e672ad2ba7',
    messagingSenderId: '697837525606',
    projectId: 'chat-app-6cd17',
    storageBucket: 'chat-app-6cd17.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCpDEAvNRW3UZlqcnVo8sR1UPrfgUhnpGc',
    appId: '1:697837525606:ios:17b5071c93e7e3b8ad2ba7',
    messagingSenderId: '697837525606',
    projectId: 'chat-app-6cd17',
    storageBucket: 'chat-app-6cd17.appspot.com',
    iosClientId: '697837525606-37hike9gor99p5vvodanrnlqtib9nadr.apps.googleusercontent.com',
    iosBundleId: 'com.example.chatting',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCpDEAvNRW3UZlqcnVo8sR1UPrfgUhnpGc',
    appId: '1:697837525606:ios:ee942cbb4d8a3595ad2ba7',
    messagingSenderId: '697837525606',
    projectId: 'chat-app-6cd17',
    storageBucket: 'chat-app-6cd17.appspot.com',
    iosClientId: '697837525606-dv5lo3j9ioksqt6as59smasb342r15hd.apps.googleusercontent.com',
    iosBundleId: 'com.example.chatting.RunnerTests',
  );
}
